permissions:
  contents: write
  issues: write
  pull-requests: write

name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许提交代码
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # 保持git凭证

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm ci

      # 阶段1: 执行语义化发布（含构建）
      - name: 自动化发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # 阶段2: 二次提交构建产物（保险措施）
      - name: 验证并提交构建产物
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 检测是否有未提交的构建产物
          if git status --porcelain | grep 'dist/'; then
            git add dist/
            git commit -m "chore(build): 补充构建产物 [skip ci]"
            git push origin main
          fi